### PR TITLE
Only hash the processed handshake

### LINKED ISSUE #75: Issue connecting to google.com or discord.com
When connecting to these endpoints, the handshake ends with an InvalidSignature error, as something in the key schedule transcript is not verified.

One difference with these hosts compared to http.sandbox.drogue.cloud, is that they batch more records into a single one in the handshake. One possibility is that there is a flaw in the decrypt/decoding logic in embedded-tls for that. 

The next step is to reproduce the 'batching' of records in the test server to see if we can reproduce the issue in the client, and then debug further.

### PR DESCRIPTION
**Pull request by bugadani**
Fixes #75 

My reproducer here was Reqwless, trying to connect to https://google.com
Before this PR, the process failed with an IncorrectHandshake error. This PR solves the cause of this error, which is incorrect updating of the transcript hash.

### CODE REVIEW

File: src/connection.rs [hunk 1]
```diff
@@ -420,45 +429,47 @@ where
...
-                ServerHandshake::CertificateRequest(request) => {
-                    trace!("Certificate requested");
-                    handshake.certificate_request.replace(request.try_into()?);
-                }
-                ServerHandshake::Finished(finished) => {
-                    trace!("************* Finished");
-                    if !key_schedule.verify_server_finished(&finished)? {
-                        return Err(TlsError::InvalidSignature);
+            ServerRecord::Handshake(server_handshake) => {
+                trace!("handshake = {:?}", server_handshake.handshake_type());
```
Comment (bugadani) [inline src/connection.rs:435]: This whole diff is just formatting change because the trace! requires a set of braces around the match.

**Comment by lulf** [comment]
Fixes #75

**Review by lulf — APPROVED** [review]
Thanks for fixing this bug! 🚀
